### ISSUE TITLE
How to use a button to control the sidebar open or close？

### ISSUE THREAD

**Issue by a2824256** [react-native-community/react-native-side-menu#265]
How to use a button to control the sidebar open or close？

**Comment by Kureev** [comment]
Hi @a2824256! I think looking into [example code](https://github.com/react-native-community/react-native-side-menu/blob/master/examples/Basic/Basic.js) is the best you can do to learn how it works.

Btw, StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by a2824256** [comment]
Ok！Thank you~I am a rookie.Orz...

**Comment by Kureev** [comment]
No problem at all 👍
