### ISSUE TITLE
autoclose not closing side menu when moving onto next screen

### ISSUE THREAD

**Issue by tharungeorgebabu** [react-native-community/react-native-side-menu#311]
autoclose not closing side menu when moving onto next screen

hence on moving back side nav is shown

on moving back we do not wnat to see the side navigation

**Comment by Kureev** [comment]
Right. So at the moment you navigate to the next screen, you can set a variable responsible for `isOpen` flag of SideMenu to `false`. 

SideMenu is not opinionated on the way you do navigation in your app, therefore there is no way we can support it on the library level (different navigation solutions use various API). Although, as I said above, you can always use `isOpen` flag in order to control menu state.

**Comment by tharungeorgebabu** [comment]
Thanks.. will try that option
